name: hangangramyeon
description: "Hangang ramyeon"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.0.0
  flutter_screenutil: ^5.9.3
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  go_router: ^14.6.3
  injectable: ^2.5.0
  animate_do: ^4.2.0
  get_it: ^8.0.3
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.2.1
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  formz: ^0.8.0
  smooth_page_indicator: ^1.2.1
  flutter_native_splash: ^2.4.3
#  intl: ^0.19.0
  esc_pos_printer_plus: ^0.1.1
  esc_pos_utils_plus: ^2.0.4
  image: ^4.1.7
  google_fonts: ^6.2.1
  persistent_bottom_nav_bar_v2: ^5.4.0
  shimmer: ^3.0.0
#  awesome_snackbar_content: ^0.1.5
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_widget_from_html: ^0.10.5
  mobile_scanner: ^6.0.10
  vibration: ^3.1.3
  image_picker: ^1.1.2
  qr_flutter: ^4.0.0
  logger: ^1.1.0
  url_launcher: ^6.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.2
  google_maps_flutter: ^2.7.0
  lottie: ^3.1.2
  #Icon
  cupertino_icons: ^1.0.8
  enefty_icons: ^1.0.8
  icons_plus: ^5.0.0
  iconly: ^1.0.1
  intl: ^0.20.2
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^6.4.1
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13
  retrofit_generator: ^9.1.5
  json_serializable: ^6.9.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
flutter_native_splash:
  color: "#E0F7FA"
  image: assets/images/logo.png
  android_gravity: center
  ios_content_mode: center